services:
  postgres:
    image: postgres:16
    container_name: routing-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=routingdb
      - POSTGRES_USER=routinguser
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: